class CreatePostPageConsts:
    TITLE_FIELD_XPATH = ".//input[@id='post-title']"
    BODY_FIELD_XPATH = ".//textarea[@id='post-body']"
    CREATE_POST_BUTTON_XPATH = ".//button[@class='btn btn-primary']"
    SUCCESS_MESSAGE_XPATH = ".//div[@class='alert alert-success text-center']"
    SUCCESS_MESSAGE_TEXT = "New post successfully created."
    DELETE_POST_XPATH = ".//button[@class= 'delete-post-button text-danger']"
    SUCCESS_DELETE_MESSAGE_XPATH = ".//div[@class = 'alert alert-success text-center']"
    SUCCESS_DELETE_MESSAGE_TEXT = "Post successfully deleted"
    EDIT_POST_BUTTON_XPATH = ".//a[@class='text-primary mr-2']"
    EDIT_MESSAGE_XPATH = ".//div[contains(text(),'Post successfully updated.')]"
    EDIT_MESSAGE_TEXT = "Post successfully updated."
    UPDATE_POST_BUTTON_XPATH = ".//button[contains(text(),'Save Updates')]"
    UPDATE_POST_TITLE_TEXT = "New title"
    UPDATE_POST_BODY_TEXT = "New message"
    CHECKBOX_XPATH = ".//input[@type='checkbox']"
